pipeline {
    agent { docker { image 'node:6.3' } }
    stages {
        stage('Build') {
            steps {
                sh 'npm --version'
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh '''
                    echo "Multiline shell steps works too"
                    ls -lah
                '''
                sh './jenkins/scripts/test.sh'
            }
        }
    }
}
